# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-pro?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    #文件上传相关配置
    multipart:
      # 开启 multipart 上传功能
      enabled: true
      #文件上传路径
      location: E:/pro/file
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB


  # 整合ES配置 本地ES安装路径 D:\SDK\elasticsearch\elasticsearch-7.13.2
  elasticsearch:
    rest:
      uris: http://localhost:9200

# Redis配置  本地Redis安装路径 D:\SDK\redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  #连接池中的最大空闲连接
        min-idle: 0   #连接池中的最小空闲连接
      shutdown-timeout: 6000ms  #连接超时时间（毫秒）

# 定时任务配置
scheduled:
  # 每隔1分钟执行一次  【秒 分 时 日 月 周】
  cronTime: 0 */1 * * * ?
